version: '3.8'

services:
  webserver:
    build:
      context: ./docker
      target: dev
    ports:
      - '8084:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - skinny-rx-test-task

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    networks:
      - skinny-rx-test-task

networks:
  skinny-rx-test-task:
